version: "3"
services:
  geoserver:
    build:
      context: .
      args:
        - GEOSERVER_VERSION=2.22.0
        - CORS_ENABLED=true
        - SSL_ENABLED=true
    ports:
      - 9090:8080
    environment:
      - INSTALL_EXTENSIONS=true
      - STABLE_EXTENSIONS=wps,csw
      - EXTRA_JAVA_OPTS=-Xms1G -Xmx2G
